services:
  daily-devtips-postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
